# Generated by Django 6.0.1 on 2026-01-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_description', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('jsonl_file', models.FileField(help_text='Upload detection .jsonl file (used once)', upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('confidence', models.FloatField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detections.survey')),
            ],
        ),
    ]
