# Generated by Django 6.0.2 on 2026-03-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='jsonl_file',
        ),
    ]
